version: '3.9'

services:
  web:
    build: .
    ports:
    - 80:80
    volumes: 
        - ./site:/var/www/html

  db:
    image: mysql
    volumes:
        - .db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 12345
        MYSQL_DATABASE: stockbarang
    ports:
        - 3306:3306